# Generated by Django 5.2.15 on 2026-08-27 05:27

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('local', 'NUMA'), ('directory', 'Annuaire')], default='local', max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('slug', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('protected', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AuditHead',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('event_hash', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('complete', 'Terminée'), ('failed', 'Échec')], default='pending', max_length=12)),
                ('destination', models.CharField(default='local', max_length=16)),
                ('encrypted', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('list', 'Liste'), ('form', 'Formulaire'), ('view', 'Vue'), ('numbering', 'Numérotation'), ('rule', 'Règle'), ('workflow', 'Workflow'), ('page', 'Page'), ('template', 'Modèle'), ('navigation', 'Navigation'), ('branding', 'Identité visuelle'), ('system', 'Système'), ('signature_policy', 'Politique de signature')], max_length=32)),
                ('slug', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=16)),
                ('data', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capabilities', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('owner', 'Créateur'), ('service', 'Service destinataire'), ('workflow', 'Workflow'), ('manual', 'Manuel')], default='manual', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(default='attachment', max_length=60)),
                ('active_version_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenericListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
                ('search_text', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=40)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('directory', 'Annuaire')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_key', models.CharField(blank=True, max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('validation', 'Validation'), ('signature', 'Signature'), ('system', 'Système'), ('deadline', 'Échéance')], default='system', max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('detail', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('email_requested', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(default='Organisation', max_length=180)),
                ('application_name', models.CharField(default='NUMA', max_length=80)),
                ('primary_color', models.CharField(default='#14532d', max_length=9)),
                ('accent_color', models.CharField(default='#ca8a04', max_length=9)),
                ('logo_data_url', models.TextField(blank=True)),
                ('favicon_data_url', models.TextField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('default_home', models.CharField(default='dashboard', max_length=40)),
                ('locale', models.CharField(default='fr-FR', max_length=12)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('configured', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('query', models.JSONField(default=dict)),
                ('shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignatureProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('electronic-validation', 'Validation électronique interne'), ('graphic', 'Signature graphique'), ('digital', 'Signature numérique qualifiée')], max_length=32)),
                ('status', models.CharField(choices=[('requested', 'Demandée'), ('verified', 'Vérifiée'), ('failed', 'Échec'), ('cancelled', 'Annulée')], default='requested', max_length=16)),
                ('signer_role', models.CharField(blank=True, max_length=120)),
                ('graphic_mark', models.TextField(blank=True)),
                ('document_hash', models.CharField(max_length=64)),
                ('evidence', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('complete', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=12)),
                ('resource_type', models.CharField(max_length=80)),
                ('source_file', models.FileField(blank=True, max_length=500, null=True, upload_to='transfers/imports/')),
                ('result_file', models.FileField(blank=True, max_length=500, null=True, upload_to='transfers/exports/')),
                ('options', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('keycloak', 'Keycloak'), ('migration', 'Migration')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(default=list)),
                ('secret_encrypted', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('completed', 'Terminé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='running', max_length=16)),
                ('current_step', models.CharField(blank=True, max_length=120)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_key', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('processing', 'Traitement'), ('validation', 'Validation'), ('signature', 'Signature')], max_length=16)),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], default='todo', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', 'due_at', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['-created_at', '-version']},
        ),
        migrations.RemoveConstraint(
            model_name='documentversion',
            name='unique_document_version',
        ),
        migrations.RemoveConstraint(
            model_name='numbersequence',
            name='unique_number_sequence',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='after',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='before',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='event_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='detected_mime_type',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='extraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Extraction en attente'), ('complete', 'Texte indexé'), ('unsupported', 'Format non pris en charge'), ('error', 'Échec de l’extraction')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='preview_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=apps.core.models.document_preview_path),
        ),
        migrations.AddField(
            model_name='numbersequence',
            name='scope_key',
            field=models.CharField(default='default', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='external_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('registered', 'Enregistré'), ('to_process', 'À traiter'), ('in_validation', 'En validation'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé'), ('signed', 'Signé'), ('archived', 'Archivé')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['resource_type', 'resource_id', 'created_at'], name='core_audite_resourc_2d1df9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'created_at'], name='core_audite_actor_i_5b4f87_idx'),
        ),
        migrations.AddConstraint(
            model_name='numbersequence',
            constraint=models.UniqueConstraint(fields=('registry', 'service_code', 'year', 'scope_key'), name='unique_number_sequence_scope'),
        ),
        migrations.AddField(
            model_name='accessgroup',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organizationunit'),
        ),
        migrations.AddField(
            model_name='accessgroup',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='groups', to='core.accessrole'),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationdefinition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_configuration_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationversion',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.configurationdefinition'),
        ),
        migrations.AddField(
            model_name='configurationversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_configuration_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configurationdefinition',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_definitions', to='core.configurationversion'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='configuration_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.configurationversion'),
        ),
        migrations.AddIndex(
            model_name='correspondence',
            index=models.Index(fields=['responsible_service', 'status'], name='core_corres_respons_bcf030_idx'),
        ),
        migrations.AddField(
            model_name='correspondenceaccessgrant',
            name='correspondence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core.correspondence'),
        ),
        migrations.AddField(
            model_name='correspondenceaccessgrant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_correspondence_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correspondenceaccessgrant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_grants', to='core.accessgroup'),
        ),
        migrations.AddField(
            model_name='correspondenceaccessgrant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='correspondence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.correspondence'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.document'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['correspondence', 'scan_status'], name='core_docume_corresp_53aa8b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['sha256'], name='core_docume_sha256_b4a1c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', False)), fields=('document', 'version'), name='unique_logical_document_version'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', True)), fields=('correspondence', 'version'), name='unique_legacy_document_version'),
        ),
        migrations.AddField(
            model_name='genericlistitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_list_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.accessgroup'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='listinstance',
            name='configuration_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.configurationversion'),
        ),
        migrations.AddField(
            model_name='listinstance',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_instances', to='core.configurationdefinition'),
        ),
        migrations.AddField(
            model_name='genericlistitem',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.listinstance'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numa_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signatureproof',
            name='correspondence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_proofs', to='core.correspondence'),
        ),
        migrations.AddField(
            model_name='signatureproof',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_proofs', to='core.documentversion'),
        ),
        migrations.AddField(
            model_name='signatureproof',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferjob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='core.accessrole'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_webhooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.webhookendpoint'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='correspondence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='core.correspondence'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='definition_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.configurationversion'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowevent',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.workflowinstance'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='assignee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_tasks', to='core.accessgroup'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_workflow_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.workflowinstance'),
        ),
        migrations.AddField(
            model_name='workflowevent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.workflowtask'),
        ),
        migrations.AddConstraint(
            model_name='accessgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_external_access_group'),
        ),
        migrations.AddConstraint(
            model_name='configurationversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version'), name='unique_configuration_version'),
        ),
        migrations.AddConstraint(
            model_name='configurationdefinition',
            constraint=models.UniqueConstraint(fields=('kind', 'slug'), name='unique_configuration_slug'),
        ),
        migrations.AddIndex(
            model_name='correspondenceaccessgrant',
            index=models.Index(fields=['correspondence', 'user'], name='core_corres_corresp_450433_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondenceaccessgrant',
            index=models.Index(fields=['correspondence', 'group'], name='core_corres_corresp_7f9dd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='correspondenceaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('user__isnull', False)), models.Q(('group__isnull', False), ('user__isnull', True)), _connector='OR'), name='correspondence_grant_one_principal'),
        ),
        migrations.AddConstraint(
            model_name='correspondenceaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('correspondence', 'user', 'source'), name='unique_correspondence_user_grant'),
        ),
        migrations.AddConstraint(
            model_name='correspondenceaccessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('correspondence', 'group', 'source'), name='unique_correspondence_group_grant'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('profile', 'group'), name='unique_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='listinstance',
            constraint=models.UniqueConstraint(fields=('definition', 'period_key'), name='unique_list_instance_period'),
        ),
        migrations.AddIndex(
            model_name='genericlistitem',
            index=models.Index(fields=['instance', 'status'], name='core_generi_instanc_2d98f6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', 'created_at'], name='core_notifi_recipie_52850f_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_saved_search_name'),
        ),
        migrations.AddConstraint(
            model_name='userroleassignment',
            constraint=models.UniqueConstraint(fields=('profile', 'role', 'source'), name='unique_user_role_source'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['assignee', 'status'], name='core_workfl_assigne_c6b511_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['assignee_group', 'status'], name='core_workfl_assigne_3c4fd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowtask',
            constraint=models.UniqueConstraint(fields=('workflow', 'step_key'), name='unique_workflow_step'),
        ),
    ]
