# Generated by Django 5.2.15 on 2026-08-27 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_enterprise_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='row_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='IdentityProviderConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.SlugField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=180)),
                ('provider', models.CharField(choices=[('oidc', 'OpenID Connect'), ('saml', 'SAML 2.0'), ('ldap', 'LDAP'), ('active_directory', 'Active Directory')], max_length=24)),
                ('enabled', models.BooleanField(default=False)),
                ('config_encrypted', models.TextField()),
                ('status', models.CharField(choices=[('untested', 'Non testé'), ('ready', 'Opérationnel'), ('error', 'Erreur')], default='untested', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('keycloak_resource_id', models.CharField(blank=True, max_length=255)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_identity_providers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_identity_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
