# Generated by Django 5.2.15 on 2026-08-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_v1_configurations_and_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='destination',
            field=models.CharField(choices=[('local', 'Stockage local'), ('s3', 'Stockage S3'), ('both', 'Local et S3')], default='both', max_length=16),
        ),
    ]
