import { useState } from 'react'
import Add from '@mui/icons-material/Add'
import BackupOutlined from '@mui/icons-material/BackupOutlined'
import CheckCircle from '@mui/icons-material/CheckCircle'
import ContentCopyOutlined from '@mui/icons-material/ContentCopyOutlined'
import DragIndicator from '@mui/icons-material/DragIndicator'
import EditOutlined from '@mui/icons-material/EditOutlined'
import History from '@mui/icons-material/History'
import PlayArrow from '@mui/icons-material/PlayArrow'
import PublishOutlined from '@mui/icons-material/PublishOutlined'
import RestoreOutlined from '@mui/icons-material/RestoreOutlined'
import Search from '@mui/icons-material/Search'
import SettingsOutlined from '@mui/icons-material/SettingsOutlined'
import {
  Alert,
  Box,
  Button,
  Card,
  Chip,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Divider,
  InputAdornment,
  LinearProgress,
  List,
  ListItemButton,
  ListItemText,
  MenuItem,
  Stack,
  Switch,
  Tab,
  Tabs,
  TextField,
  Typography,
} from '@mui/material'
import { Link as RouterLink, useParams } from 'react-router-dom'
import { NumberingBuilderPanel } from '../components/NumberingBuilderPanel'
import { usePrototypeData } from '../app/PrototypeDataContext'

const adminModules = [
  ['/administration/site', 'Identité visuelle', 'Logo de l’entreprise et identité affichée'],
  ['/administration/utilisateurs', 'Utilisateurs et accès', 'Annuaire, groupes, rôles et permissions fines'],
  ['/administration/navigation', 'Navigation', 'Menus, ordre et visibilité par permission'],
  ['/administration/listes', 'Listes et formulaires', 'Champs, vues, numérotation, règles et permissions'],
  ['/administration/regles', 'Règles métier', 'Conditions, actions, tests et versions'],
  ['/administration/pages', 'Pages et navigation', 'Composition responsive et publication'],
  ['/administration/templates', 'Templates', 'Modèles métier versionnés et réutilisables'],
  ['/administration/workflows', 'Workflows', 'États, transitions, acteurs et automatisations'],
  ['/administration/audit', 'Audit', 'Événements métier et techniques traçables'],
  ['/administration/sauvegardes', 'Sauvegardes', 'Rétention et restauration sécurisée'],
  ['/administration/exploitation', 'Exploitation', 'Services, stockage, alertes et intégrations'],
  ['/administration/parametres', 'Paramètres système', 'Sécurité, fichiers, notifications et langue'],
]

export function AdministrationOverviewPage() {
  return <Box sx={{ maxWidth: 1200, mx: 'auto', px: { xs: 2, sm: 3, lg: 4 }, py: { xs: 3, md: 4 } }}><Typography component="h1" variant="h1">Administration</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.75, mb: 3 }}>Configurez NUMA sans modifier son cœur applicatif.</Typography><Alert severity="info" sx={{ mb: 2.5 }}>Vous travaillez avec le rôle Configurateur. Les opérations sensibles restent soumises aux permissions fines.</Alert><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(2, 1fr)' }, gap: 2 }}>{adminModules.map(([path, title, description]) => <Card key={path} sx={{ p: 2.5 }}><SettingsOutlined color="primary" /><Typography component="h2" variant="h2" sx={{ mt: 1.5 }}>{title}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.75 }}>{description}</Typography><Button component={RouterLink} to={path} sx={{ mt: 1.5, px: 0 }}>Configurer</Button></Card>)}</Box></Box>
}

const listSections = ['Paramètres', 'Champs', 'Formulaire', 'Vues', 'Cycle annuel', 'Numérotation', 'Règles', 'Workflow', 'Permissions', 'Publication']

export function ListBuilderPage() {
  const { id = 'courriers-externes' } = useParams()
  const { lists } = usePrototypeData()
  const definition = lists.find((item) => item.id === id) ?? lists[0]
  const [section, setSection] = useState('Champs')
  const [published, setPublished] = useState(false)
  return <Box sx={{ maxWidth: 1440, mx: 'auto', px: { xs: 2, sm: 3 }, py: 3 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'flex-start' }} spacing={2} sx={{ mb: 2.5 }}><Box><Typography component="h1" variant="h1">Configuration — {definition?.name ?? 'Liste'}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.75 }}>Définition de liste · {definition?.version ?? 'v1'} publiée · brouillon suivant</Typography></Box><Stack direction="row" spacing={1}><Button component={RouterLink} to={`/administration/listes/${id}/formulaire`} variant="outlined">Prévisualiser</Button><Button variant="contained" startIcon={<PublishOutlined />} onClick={() => setPublished(true)}>Publier</Button></Stack></Stack>{published ? <Alert severity="success" sx={{ mb: 2 }}>La nouvelle version est publiée. Les prochaines créations utilisent cette configuration.</Alert> : null}<Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '230px minmax(0, 1fr)' }, gap: 2 }}><Card sx={{ alignSelf: 'start' }}><List disablePadding>{listSections.map((item) => <ListItemButton key={item} selected={section === item} onClick={() => setSection(item)}><ListItemText primary={item} primaryTypographyProps={{ fontSize: 13, fontWeight: section === item ? 700 : 500 }} /></ListItemButton>)}</List></Card><Card><Box sx={{ p: 2.5 }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography component="h2" variant="h2">{section}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>Configuration visuelle et règles applicables à la liste.</Typography></Box><Button startIcon={<Add />}>Ajouter</Button></Stack></Box><Divider />
  {section === 'Champs' ? <Stack divider={<Divider flexItem />}>{[['Objet', 'Texte court · Obligatoire'], ['Expéditeur', 'Texte court · Obligatoire'], ['Date de réception', 'Date · Obligatoire'], ['Direction destinataire', 'Liste de choix · Obligatoire'], ['Priorité', 'Liste de choix · Valeur par défaut : Normale'], ['Confidentialité', 'Liste de choix · Conditionnelle']].map(([name, detail]) => <Stack key={name} direction="row" alignItems="center" spacing={1.5} sx={{ p: 2 }}><DragIndicator color="disabled" /><Box sx={{ flex: 1 }}><Typography fontWeight={700}>{name}</Typography><Typography variant="caption" color="text.secondary">{detail}</Typography></Box><Button startIcon={<EditOutlined />} size="small">Configurer</Button></Stack>)}</Stack> : null}
  {section === 'Numérotation' ? <NumberingBuilderPanel /> : null}
  {section === 'Workflow' ? <Box sx={{ p: 2.5 }}><Typography fontWeight={700}>Workflow actif : Courrier externe — standard</Typography><Stack direction="row" spacing={1} sx={{ mt: 2, overflowX: 'auto', pb: 1 }}>{['Brouillon', 'Chef de service', 'Direction', 'Signature', 'Enregistré', 'Archivé'].map((state, index) => <Stack key={state} direction="row" alignItems="center" spacing={1}><Chip label={state} color={index === 0 ? 'primary' : 'default'} /><Typography color="text.disabled">{index < 5 ? '→' : ''}</Typography></Stack>)}</Stack><Button component={RouterLink} to="/administration/workflows" variant="outlined" sx={{ mt: 2 }}>Ouvrir le Workflow Builder</Button></Box> : null}
  {section === 'Formulaire' ? <Box sx={{ p: 2.5 }}><Alert severity="info">Le formulaire possède une mise en page, des conditions d'affichage et des calculs propres.</Alert><Button component={RouterLink} to={`/administration/listes/${id}/formulaire`} variant="contained" sx={{ mt: 2 }}>Ouvrir le Form Builder</Button></Box> : null}
  {section === 'Paramètres' ? <Stack spacing={1.5} sx={{ p: 2.5 }}><TextField label="Nom d'affichage" defaultValue={definition?.name} /><TextField label="Description" defaultValue={definition?.description} multiline minRows={2} /><TextField select label="Périodicité" defaultValue={definition?.periodicity ?? 'annual'}><MenuItem value="annual">Annuelle</MenuItem><MenuItem value="continuous">Continue</MenuItem></TextField><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography fontWeight={700}>Liste active</Typography><Typography variant="caption" color="text.secondary">Visible pour les utilisateurs autorisés</Typography></Box><Switch defaultChecked={definition?.status === 'Publié'} /></Stack></Stack> : null}
  {section === 'Vues' ? <Stack spacing={1.5} sx={{ p: 2.5 }}>{[['Tous les courriers', 'Tableau'], ['Mes courriers', 'Tableau filtré'], ['Par direction', 'Vue groupée']].map(([name, type]) => <Card key={name} variant="outlined" sx={{ p: 2 }}><Stack direction="row" justifyContent="space-between"><Box><Typography fontWeight={700}>{name}</Typography><Typography variant="caption" color="text.secondary">{type} · tri et colonnes configurables</Typography></Box><Button size="small">Configurer</Button></Stack></Card>)}</Stack> : null}
  {section === 'Cycle annuel' ? <Box sx={{ p: 2.5 }}><Typography fontWeight={700}>Création automatique au 1er janvier</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>Clôture de l'instance précédente, conservation en lecture seule et reprise de la séquence.</Typography><Button component={RouterLink} to="/administration/instances" variant="outlined" sx={{ mt: 2 }}>Gérer les instances</Button></Box> : null}
  {section === 'Règles' ? <Box sx={{ p: 2.5 }}><Typography fontWeight={700}>3 règles actives pour cette liste</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>Contrôles, calculs et automatisations déclenchés selon les événements.</Typography><Button component={RouterLink} to="/administration/regles" variant="outlined" sx={{ mt: 2 }}>Gérer les règles</Button></Box> : null}
  {section === 'Permissions' ? <Stack spacing={1.5} sx={{ p: 2.5 }}>{['Consulter', 'Créer', 'Modifier', 'Valider', 'Administrer'].map((permission, index) => <Stack key={permission} direction="row" justifyContent="space-between" alignItems="center"><Typography>{permission}</Typography><Chip label={index < 3 ? 'Agent courrier, Validateur, Admin' : 'Validateur, Admin'} size="small" variant="outlined" /></Stack>)}<Button component={RouterLink} to="/administration/permissions" variant="outlined">Ouvrir la matrice complète</Button></Stack> : null}
  {section === 'Publication' ? <Box sx={{ p: 2.5 }}><Alert severity={published ? 'success' : 'warning'}>{published ? 'La configuration courante est publiée.' : 'Le brouillon comporte des changements non publiés.'}</Alert><Stack spacing={1} sx={{ mt: 2 }}>{['Champs valides', 'Formulaire accessible', 'Workflow sans transition orpheline', 'Permissions attribuées'].map((item) => <Stack key={item} direction="row" spacing={1} alignItems="center"><CheckCircle color="success" fontSize="small" /><Typography variant="body2">{item}</Typography></Stack>)}</Stack><Button variant="contained" startIcon={<PublishOutlined />} sx={{ mt: 2 }} onClick={() => setPublished(true)}>Publier cette version</Button></Box> : null}
  </Card></Box></Box>
}

export function PageBuilderPage() {
  const [viewport, setViewport] = useState('desktop')
  return <Box sx={{ px: { xs: 2, sm: 3 }, py: 3 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'flex-start' }} spacing={2} sx={{ mb: 2 }}><Box><Typography component="h1" variant="h1">Page Builder — Accueil DT</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>Brouillon · modifications enregistrées automatiquement</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined">Aperçu</Button><Button variant="contained" startIcon={<PublishOutlined />}>Publier</Button></Stack></Stack><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: '240px minmax(0, 1fr) 280px' }, gap: 1.5 }}><Card sx={{ p: 2, alignSelf: 'start' }}><Typography component="h2" variant="h3">Composants</Typography><Stack spacing={1} sx={{ mt: 1.5 }}>{['Titre', 'Texte', 'Indicateurs', 'Graphique', 'Liste', 'Bouton', 'Séparateur'].map((component) => <Button key={component} variant="outlined" startIcon={<DragIndicator />} sx={{ justifyContent: 'flex-start' }}>{component}</Button>)}</Stack></Card><Card sx={{ p: 2, minHeight: 620, bgcolor: '#EDF1F7' }}><Tabs value={viewport} onChange={(_, value: string) => setViewport(value)} centered><Tab value="desktop" label="Bureau" /><Tab value="tablet" label="Tablette" /><Tab value="mobile" label="Mobile" /></Tabs><Box sx={{ width: viewport === 'mobile' ? 360 : viewport === 'tablet' ? 680 : '100%', maxWidth: '100%', mx: 'auto', mt: 2, bgcolor: 'white', minHeight: 520, p: 2.5, transition: 'width .2s' }}><Typography variant="h2">Bonjour, équipe DT</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>Votre activité du jour</Typography><Box sx={{ display: 'grid', gridTemplateColumns: viewport === 'mobile' ? '1fr' : 'repeat(3, 1fr)', gap: 1.5, mt: 2 }}>{['12 à traiter', '4 validations', '2 signatures'].map((text) => <Card key={text} sx={{ p: 2 }}><Typography fontWeight={700}>{text}</Typography></Card>)}</Box><Box sx={{ mt: 2, p: 4, border: '2px dashed', borderColor: 'primary.light', textAlign: 'center' }}><Typography color="text.secondary">Déposez un composant ici</Typography></Box></Box></Card><Card sx={{ p: 2, alignSelf: 'start' }}><Typography component="h2" variant="h3">Propriétés</Typography><Stack spacing={1.5} sx={{ mt: 1.5 }}><TextField size="small" label="Titre" defaultValue="Votre activité du jour" /><TextField size="small" label="Largeur" select defaultValue="12"><MenuItem value="12">12 colonnes</MenuItem><MenuItem value="6">6 colonnes</MenuItem></TextField><TextField size="small" label="Visibilité" select defaultValue="dt"><MenuItem value="dt">Direction Technique</MenuItem><MenuItem value="all">Tous</MenuItem></TextField><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="body2">Afficher sur mobile</Typography><Switch defaultChecked /></Stack></Stack></Card></Box></Box>
}

export function TemplatesPage() {
  const templates = [['Courrier externe standard', 'Courrier', 'v8', 'Publié'], ['Demande Direction Technique', 'Formulaire', 'v4', 'Publié'], ['Validation à deux niveaux', 'Workflow', 'v6', 'Brouillon'], ['Accueil de direction', 'Page', 'v3', 'Publié']]
  return <Box sx={{ maxWidth: 1200, mx: 'auto', px: { xs: 2, sm: 3 }, py: 3 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'flex-start' }} spacing={2} sx={{ mb: 2.5 }}><Box><Typography component="h1" variant="h1">Templates</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>Catalogue des modèles métier versionnés.</Typography></Box><Button variant="contained" startIcon={<Add />}>Nouveau template</Button></Stack><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)' }, gap: 2 }}>{templates.map(([name, type, version, status]) => <Card key={name} sx={{ p: 2.5 }}><Stack direction="row" justifyContent="space-between"><Chip label={type} size="small" variant="outlined" /><Chip label={status} size="small" color={status === 'Publié' ? 'success' : 'default'} /></Stack><Typography component="h2" variant="h3" sx={{ mt: 2 }}>{name}</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>{version} · mis à jour le 12/08/2026</Typography><Stack direction="row" spacing={1} sx={{ mt: 2 }}><Button startIcon={<EditOutlined />}>Modifier</Button><Button startIcon={<ContentCopyOutlined />}>Dupliquer</Button></Stack></Card>)}</Box></Box>
}

export function WorkflowBuilderPage() {
  const [tested, setTested] = useState(false)
  const states = ['Brouillon', 'Soumis', 'Chef de service', 'Direction', 'Signature', 'Enregistré', 'Archivé']
  return <Box sx={{ maxWidth: 1400, mx: 'auto', px: { xs: 2, sm: 3 }, py: 3 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'flex-start' }} spacing={2} sx={{ mb: 2.5 }}><Box><Typography component="h1" variant="h1">Workflow Builder</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>Courrier externe — standard · brouillon v7</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<PlayArrow />} onClick={() => setTested(true)}>Tester</Button><Button variant="contained" startIcon={<PublishOutlined />}>Publier</Button></Stack></Stack>{tested ? <Alert severity="success" sx={{ mb: 2 }}>Simulation réussie : 7 états, 6 transitions et 2 conditions vérifiés.</Alert> : null}<Card sx={{ p: 3, overflowX: 'auto' }}><Stack direction="row" alignItems="flex-start" spacing={1} sx={{ minWidth: 940, py: 3 }}>{states.map((state, index) => <Stack key={state} direction="row" alignItems="center" spacing={1} sx={{ flex: 1 }}><Card variant="outlined" sx={{ p: 2, minWidth: 118, textAlign: 'center', borderColor: index === 4 ? 'primary.main' : 'divider', boxShadow: 'none' }}><Typography fontWeight={700} variant="body2">{state}</Typography><Typography variant="caption" color="text.secondary">{index === 0 ? 'Auteur' : index === 6 ? 'Système' : 'Rôle assigné'}</Typography></Card>{index < states.length - 1 ? <Typography color="primary">→</Typography> : null}</Stack>)}</Stack></Card><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 2, mt: 2 }}><Card sx={{ p: 2.5 }}><Typography component="h2" variant="h3">Transition sélectionnée</Typography><Stack spacing={1.5} sx={{ mt: 2 }}><TextField label="Nom" defaultValue="Direction → Signature" /><TextField label="Condition" defaultValue="validation.accepted == true" /><TextField label="Acteur cible" select defaultValue="signer"><MenuItem value="signer">Signataire habilité</MenuItem></TextField></Stack></Card><Card sx={{ p: 2.5 }}><Typography component="h2" variant="h3">Actions automatiques</Typography><Stack spacing={1.5} sx={{ mt: 2 }}>{['Demander une signature', 'Notifier le signataire', 'Créer une tâche avec échéance'].map((action) => <Stack key={action} direction="row" justifyContent="space-between" alignItems="center"><Typography variant="body2">{action}</Typography><Switch defaultChecked /></Stack>)}</Stack></Card></Box></Box>
}

export function AuditPage() {
  const events = [['15/08/2026 15:48:22', 'Kader Yao', 'Signature', 'EXT-0040/2026', 'Signature graphique · v3'], ['15/08/2026 14:05:11', 'Awa Kouassi', 'Validation', 'EXT-0052/2026', 'Direction → Signature'], ['15/08/2026 11:12:04', 'Mariam Diarra', 'Rejet', 'EXT-0039/2026', 'Pièce justificative manquante'], ['15/08/2026 09:00:00', 'Système', 'Import', 'Externe 2026', '1 218 lignes créées']]
  return <Box sx={{ maxWidth: 1300, mx: 'auto', px: { xs: 2, sm: 3 }, py: 3 }}><Typography component="h1" variant="h1">Journal d’audit</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5, mb: 2.5 }}>Traçabilité immuable des événements métier et techniques.</Typography><Card sx={{ mb: 2 }}><Box sx={{ p: 2, display: 'grid', gridTemplateColumns: { xs: '1fr', md: '2fr 1fr 1fr' }, gap: 1.5 }}><TextField size="small" placeholder="Acteur, ressource ou détail…" slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search /></InputAdornment> } }} /><TextField size="small" select label="Action" defaultValue=""><MenuItem value="">Toutes</MenuItem><MenuItem value="signature">Signature</MenuItem><MenuItem value="validation">Validation</MenuItem></TextField><TextField size="small" type="date" label="Date" defaultValue="2026-08-15" slotProps={{ inputLabel: { shrink: true } }} /></Box></Card><Card><Stack divider={<Divider flexItem />}>{events.map(([date, actor, action, resource, detail]) => <Box key={`${date}-${action}`} sx={{ p: 2, display: 'grid', gridTemplateColumns: { xs: '1fr', md: '180px 150px 140px 180px 1fr' }, gap: 1.5 }}><Typography variant="caption" sx={{ fontFamily: 'IBM Plex Mono, monospace' }}>{date}</Typography><Typography variant="body2" fontWeight={700}>{actor}</Typography><Chip label={action} size="small" variant="outlined" sx={{ justifySelf: 'start' }} /><Typography variant="body2" color="primary">{resource}</Typography><Typography variant="body2" color="text.secondary">{detail}</Typography></Box>)}</Stack></Card></Box>
}

export function BackupsPage() {
  const [restoreOpen, setRestoreOpen] = useState(false)
  const [reason, setReason] = useState('')
  const backups = [['15/08/2026 · 03:00', 'Incrémentale', '184 Mo', 'Réussie'], ['14/08/2026 · 03:00', 'Incrémentale', '176 Mo', 'Réussie'], ['10/08/2026 · 03:00', 'Complète', '2,4 Go', 'Réussie'], ['09/08/2026 · 03:00', 'Incrémentale', '—', 'Échouée']]
  return <Box sx={{ maxWidth: 1200, mx: 'auto', px: { xs: 2, sm: 3 }, py: 3 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'flex-start' }} spacing={2} sx={{ mb: 2.5 }}><Box><Typography component="h1" variant="h1">Sauvegardes et restauration</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>Restauration réservée au Super administrateur et toujours auditée.</Typography></Box><Button variant="contained" startIcon={<BackupOutlined />}>Lancer une sauvegarde</Button></Stack><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1.5fr 1fr' }, gap: 2, mb: 2 }}><Card sx={{ p: 2.5 }}><Typography component="h2" variant="h3">Planification</Typography><Typography variant="body2" sx={{ mt: 1.5 }}>Quotidienne · 03:00 UTC</Typography><Typography variant="body2" color="text.secondary">Complète chaque dimanche + incrémentale quotidienne · rétention 30 jours · stockage chiffré hors site.</Typography></Card><Alert severity="warning"><strong>Restauration destructive</strong><br />Confirmation renforcée et justification obligatoires avant exécution.</Alert></Box><Card><Box sx={{ p: 2.5 }}><Typography component="h2" variant="h2">Historique</Typography></Box><Divider /><Stack divider={<Divider flexItem />}>{backups.map(([date, type, size, status]) => <Box key={date} sx={{ p: 2, display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '1.2fr 1fr .7fr .8fr auto' }, gap: 1.5, alignItems: 'center' }}><Typography variant="body2" fontWeight={700}>{date}</Typography><Typography variant="body2">{type}</Typography><Typography variant="body2">{size}</Typography><Chip label={status} size="small" color={status === 'Réussie' ? 'success' : 'error'} variant="outlined" sx={{ justifySelf: 'start' }} /><Stack direction="row"><Button size="small">Journal</Button><Button size="small" startIcon={<RestoreOutlined />} disabled={status !== 'Réussie'} onClick={() => setRestoreOpen(true)}>Restaurer</Button></Stack></Box>)}</Stack></Card><Dialog open={restoreOpen} onClose={() => setRestoreOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Préparer la restauration</DialogTitle><DialogContent><Alert severity="error" sx={{ mb: 2 }}>La restauration remplace l’état courant du périmètre sélectionné. Une sauvegarde de sécurité sera créée avant exécution.</Alert><TextField fullWidth required multiline minRows={4} label="Justification" value={reason} onChange={(event) => setReason(event.target.value)} /></DialogContent><DialogActions><Button onClick={() => setRestoreOpen(false)}>Annuler</Button><Button variant="contained" color="error" disabled={!reason.trim()}>Continuer avec authentification renforcée</Button></DialogActions></Dialog></Box>
}

export function OperationsPage() {
  const services = [['API Django', 'Opérationnel', '82 ms'], ['PostgreSQL', 'Opérationnel', '18 ms'], ['MinIO Documents', 'Opérationnel', '64 % utilisé'], ['Celery / Redis', 'Dégradé', '3 tâches en reprise']]
  return <Box sx={{ maxWidth: 1200, mx: 'auto', px: { xs: 2, sm: 3 }, py: 3 }}><Typography component="h1" variant="h1">État de la plateforme</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5, mb: 2.5 }}>Supervision fonctionnelle des services, du stockage et des intégrations.</Typography><Alert severity="warning" sx={{ mb: 2.5 }}>Le traitement asynchrone est dégradé : trois tâches seront automatiquement rejouées.</Alert><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)' }, gap: 1.5 }}>{services.map(([service, status, detail]) => <Card key={service} sx={{ p: 2.5 }}><Stack direction="row" justifyContent="space-between"><Typography component="h2" variant="h3">{service}</Typography><Chip label={status} size="small" color={status === 'Opérationnel' ? 'success' : 'warning'} variant="outlined" /></Stack><Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>{detail}</Typography>{service === 'MinIO Documents' ? <LinearProgress variant="determinate" value={64} sx={{ mt: 1.5 }} /> : null}</Card>)}</Box><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 2, mt: 2 }}><Card sx={{ p: 2.5 }}><Typography component="h2" variant="h2">Webhooks</Typography><Stack spacing={1.25} sx={{ mt: 2 }}>{['courrier.created', 'workflow.validated', 'signature.completed'].map((event) => <Stack key={event} direction="row" justifyContent="space-between"><Typography variant="body2" sx={{ fontFamily: 'IBM Plex Mono, monospace' }}>{event}</Typography><Chip label="Actif" size="small" color="success" /></Stack>)}</Stack><Button variant="outlined" sx={{ mt: 2 }}>Configurer les intégrations</Button></Card><Card sx={{ p: 2.5 }}><Typography component="h2" variant="h2">Documentation API</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>OpenAPI v3 · authentification OIDC · environnement interne.</Typography><Button variant="outlined" sx={{ mt: 2 }}>Ouvrir la documentation</Button></Card></Box></Box>
}
